name: '[AutoGen nuget] Build and test'

on:
  workflow_call:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dotnet
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install jupyter and ipykernel
      run: |
        python -m pip install --upgrade pip
        python -m pip install jupyter
        python -m pip install ipykernel
    - name: list available kernels
      run: |
        python -m jupyter kernelspec list
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install .NET Aspire workload
      run: dotnet workload install aspire
    - name: Restore dependencies
      run: dotnet restore AutoGen.sln
    - name: Build
      run: dotnet build AutoGen.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal AutoGen.sln
